In [1]:
import json
import os
import pandas as pd
import numpy as np
import preprocessor
from pyvi import ViTokenizer
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_recall_curve, auc, classification_report, precision_recall_fscore_support
from sklearn.svm import SVC
from sklearn import svm, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support as score

In [2]:
path_json = '../data/raw_data'

In [3]:
path_urls = os.path.join(path_json,'urls.txt')

In [4]:
with open(path_urls,"rb") as input_file:
    urls = input_file.readlines()

In [5]:
len(urls)

1008

In [6]:
comment_score = {'comment':[]}

In [7]:
for index,url in enumerate(urls):
    try:
        path_index_json = os.path.join(path_json,'{:03d}.json'.format(index))
        with open(path_index_json,"rb") as input_file:
            data = json.load(input_file)
        comment_score['comment'].extend(data['comment'])
    except:
        pass

In [8]:
data_comment = {'comment':[],'score':[]}

In [9]:
for i,text in enumerate(comment_score['comment']):
    data_comment['comment'].append(text['comment'])
    try:
        data_comment['score'].append(text['score'])
    except:
        data_comment['score'].append(-100)

In [10]:
df = pd.DataFrame(data_comment) 

import preprocessor

from pyvi import ViTokenizer
with open("/home/hieuvt/Projects/Crawl_comments/vietnamese-stopwords-dash.txt", encoding="utf8") as input_file:
    x = input_file.readlines()
    removetable = str.maketrans('', '', '\n')
    stopwords = [s.translate(removetable) for s in x]
def prepocess(text):
    return preprocessor.preprocess(text)
def tokenize(text, stopwords):
        text_segmented = ViTokenizer.tokenize(text).split()
        text_segmented = [elem for elem in text_segmented if elem not in stopwords]
        return ' '.join(text_segmented)

reviews = []
score_comment = []

for i, text in enumerate(comment_score['comment']):
    try:
        score_comment.append(text['score'])
    except:
        score_comment.append(-100)
    a = prepocess(text['comment'])
    reviews.append(tokenize(a,stopwords))

X.shape

In [11]:
df

comment score
0     Quán ưu thích của mình, lâu lâu mới thấy giảm ...    10
1                   Chân gà ngon lắm, mình hay ăn ở đây   8.0
2                               Chân gà ngon nha cả nhà   9.6
3     Cuối tuần thèm chân gà, quán quen ăn gần chục ...    10
4     Chân gà tươi ngon, rút xương sạch sẽ, chân to ...    10
5     Thấy shop giảm giá tốt nên dùng thử, chân gà t...   9.0
6     Chân gà rút xương nhưng vẫn giòn và dai, thấm ...   9.0
7     Quán đang giảm 20% nhập mã NOW3TUOI giảm ...    10
8     Mới vừa nhận hàng xong, châm gà trắng nhách, s...   3.2
9     Cuối tuần rảnh rang đặt chân gà ăn chơi, chân ...   8.2
10    Hình sp khác, nhận hàng khác nhau quá chừng. S...   5.0
11    Mùa mưa tới rồi, order đồ ăn dự trữ sẵn thôi, ...   8.4
12    Chân gà tươi ngon làm kỹ, mùi vị khá hơn mấy q...   7.0
13    Mình hay mua chân gà rút xương của shop, hôm n...   9.0
14    Lần thứ ba mua và ko bao giờ trở lại nữa\nMới ...   1.8
15    Quán bán có tâm xíu đi,chân gà nhạt hơn nước ố...   3.2
16    Lần 2 mua có note xin thêm hợp nước chấm shop ...   4.2
17    Chân gà làm ko kỹ, ko thèm cắt cả phần cùi món...   5.0
18    Chỉ có 125k hộp nửa kí mà chân nào cũng to béo...   8.0
19    Đây là lần thứ hai mình order, nhưng chân gà c...   3.8
20    Chân gà màu tự nhiên không giống các loại tẩy ...   8.0
21    Hôm nay vừa đặt 1 hộp cả nhà ăn hết ai cũng kh...   8.8
22    Hôm nay tự nhiên thấy thèm món này nên order v...   7.8
23    Trưa nóng ngán cơm mình ăn chân gà vậy, chân g...   8.0
24    Lần đầu shop làm hơi ngọt và ít cay, mới bán n...   8.2
25    Thèm chân gà mấy hôm nay mà shop nghỉ, hôm nay...   8.0
26    Mưa to từ chiều tới giờ chưa tạnh đành núp luô...   8.2
27    Ngày lễ mà trời nắng nóng quá, ở nhà ăn chân g...   8.0
28    Ngon. Nhìn sạch sẽ, chân gà giòn, rút xương kỹ...   8.4
29    Chân gà rút xương ăn rất tuyệt lại nhiều nữa, ...   8.0
...                                                 ...   ...
2934  Lúc mình biết đi thì quán đã có rồi, mẹ toàn d...   7.6
2935  Ngon nhưng giá hơi cao\nLúc ít lúc nhiều số lư...   5.4
2936  Không gian:\n- Nhiều cây xanh nhỏ nhỏ rất xinh...   8.6
2937  Tuần trước nhà có việc mời nhiều khách của bố ...   5.0
2938  Mình đã đến đây, quán mới nên đồ uống khá chất...   7.6
2939  Thề là không bao giờ quay lại đây nữa. Đồ uống...   1.0
2940  Gọi đồ uống nóng thì nguội ngắt. Gọi bánh thì ...   4.4
2941                              Đồ uống siêu chán lun   3.2
2942                   Uống cafe, fast food, take away.   7.2
2943  + không gian thoáng, bài trí đẹp, yên tĩnh\n+ ...   6.0
2944  Đồ uống khá là ổn, vừa miệng và ko bị lợ. Khôn...   8.4
2945  Đây là quán cafe khá ưng ở Nam Định\nDễ tìm, q...   7.8
2946  Quán nè không gian đẹp, đã đc sửa đổi nhiều so...   8.2
2947  Mình cùng bạn đến quán. Ấn tượng đầu tiên là q...   7.4
2948  Đợt tết có ăn ở đây lẩu, k biết nó có phải là ...   5.2
2949  Sinh nhật 20 tuổi mình tổ chức tại đây. Chỉ 2-...   7.8
2950  Quán yên tĩnh có điều hoà nên ngày nóng dc trố...   7.6
2951  Đi tìm quán để ăn 5.6 lần không thấy quán.Nhìn...   1.0
2952  Bún mộc khá ngon, mộc thơm, vị đậm đà. Nước dù...   7.0
2953  Đi ăn với các phụ huynh nên chụp được mỗi một ...   8.2
2954  Quán nhỏ xíu. Đc tầm 6 bàn. Nhưng phở ăn khá đ...   7.2
2955  Hôm nay về Nam Định, thèm hải sản mới mò thử đ...   2.0
2956  🥗 Hôm cậu bạn tặng cho túi nem nắm, mình là tí...   7.2
2957  Quán cafe khá to nằm ngay mặt đường lớn. Chủ q...   8.0
2958  mỗii lần có người thân ngoài bắc vào nhà mình ...   7.2
2959  Ấn tượng bởi hương vị của bắp rang bơ\nNhiều l...   7.4
2960  Vừa qua lễ 30/4 nên có nhiều người quen đi du ...   7.0
2961                                      kẹo Sìu Châu.   6.6
2962  Mình thây quán này không gian rất thỏa mái tra...   7.0
2963  Trong cái nắng hè oi ả với nhiệt độ ngoài trời...   7.0

[2964 rows x 2 columns]

In [12]:
df[df['score'] == -100]

comment score
843   Món ăn:\n- Ca cao dừa là món must-try của quán...  -100
1717  Ở gần nhà có quán cafe này. Đến tầm 6h thì quá...  -100

df.loc[df.score == -100,'score'] = 8

In [13]:
df.iloc[843]

comment    Món ăn:\n- Ca cao dừa là món must-try của quán...
score                                                   -100
Name: 843, dtype: object

In [14]:
df.iloc[1717]

comment    Ở gần nhà có quán cafe này. Đến tầm 6h thì quá...
score                                                   -100
Name: 1717, dtype: object

In [15]:
df.loc[df.score == -100,'score'][843] = 4

In [16]:
df.loc[df.score == -100,'score'][1717] = 9

In [17]:
df.iloc[843].score = 4

In [18]:
df.iloc[1717].score = 9

In [19]:
df.loc[df.score == -100,'score']

Series([], Name: score, dtype: object)

In [20]:
int(df['score'].iloc[0]) >= 6.0

True

In [21]:
df['score'].values

array(['10', '8.0', '9.6', ..., '6.6', '7.0', '7.0'], dtype=object)

In [22]:
for i,ele in enumerate(df['score'].values):
    if (float(ele) >= 6.0):
        df.iloc[i].score = 1
    else:
        df.iloc[i].score = 0

In [23]:
df

comment score
0     Quán ưu thích của mình, lâu lâu mới thấy giảm ...     1
1                   Chân gà ngon lắm, mình hay ăn ở đây     1
2                               Chân gà ngon nha cả nhà     1
3     Cuối tuần thèm chân gà, quán quen ăn gần chục ...     1
4     Chân gà tươi ngon, rút xương sạch sẽ, chân to ...     1
5     Thấy shop giảm giá tốt nên dùng thử, chân gà t...     1
6     Chân gà rút xương nhưng vẫn giòn và dai, thấm ...     1
7     Quán đang giảm 20% nhập mã NOW3TUOI giảm ...     1
8     Mới vừa nhận hàng xong, châm gà trắng nhách, s...     0
9     Cuối tuần rảnh rang đặt chân gà ăn chơi, chân ...     1
10    Hình sp khác, nhận hàng khác nhau quá chừng. S...     0
11    Mùa mưa tới rồi, order đồ ăn dự trữ sẵn thôi, ...     1
12    Chân gà tươi ngon làm kỹ, mùi vị khá hơn mấy q...     1
13    Mình hay mua chân gà rút xương của shop, hôm n...     1
14    Lần thứ ba mua và ko bao giờ trở lại nữa\nMới ...     0
15    Quán bán có tâm xíu đi,chân gà nhạt hơn nước ố...     0
16    Lần 2 mua có note xin thêm hợp nước chấm shop ...     0
17    Chân gà làm ko kỹ, ko thèm cắt cả phần cùi món...     0
18    Chỉ có 125k hộp nửa kí mà chân nào cũng to béo...     1
19    Đây là lần thứ hai mình order, nhưng chân gà c...     0
20    Chân gà màu tự nhiên không giống các loại tẩy ...     1
21    Hôm nay vừa đặt 1 hộp cả nhà ăn hết ai cũng kh...     1
22    Hôm nay tự nhiên thấy thèm món này nên order v...     1
23    Trưa nóng ngán cơm mình ăn chân gà vậy, chân g...     1
24    Lần đầu shop làm hơi ngọt và ít cay, mới bán n...     1
25    Thèm chân gà mấy hôm nay mà shop nghỉ, hôm nay...     1
26    Mưa to từ chiều tới giờ chưa tạnh đành núp luô...     1
27    Ngày lễ mà trời nắng nóng quá, ở nhà ăn chân g...     1
28    Ngon. Nhìn sạch sẽ, chân gà giòn, rút xương kỹ...     1
29    Chân gà rút xương ăn rất tuyệt lại nhiều nữa, ...     1
...                                                 ...   ...
2934  Lúc mình biết đi thì quán đã có rồi, mẹ toàn d...     1
2935  Ngon nhưng giá hơi cao\nLúc ít lúc nhiều số lư...     0
2936  Không gian:\n- Nhiều cây xanh nhỏ nhỏ rất xinh...     1
2937  Tuần trước nhà có việc mời nhiều khách của bố ...     0
2938  Mình đã đến đây, quán mới nên đồ uống khá chất...     1
2939  Thề là không bao giờ quay lại đây nữa. Đồ uống...     0
2940  Gọi đồ uống nóng thì nguội ngắt. Gọi bánh thì ...     0
2941                              Đồ uống siêu chán lun     0
2942                   Uống cafe, fast food, take away.     1
2943  + không gian thoáng, bài trí đẹp, yên tĩnh\n+ ...     1
2944  Đồ uống khá là ổn, vừa miệng và ko bị lợ. Khôn...     1
2945  Đây là quán cafe khá ưng ở Nam Định\nDễ tìm, q...     1
2946  Quán nè không gian đẹp, đã đc sửa đổi nhiều so...     1
2947  Mình cùng bạn đến quán. Ấn tượng đầu tiên là q...     1
2948  Đợt tết có ăn ở đây lẩu, k biết nó có phải là ...     0
2949  Sinh nhật 20 tuổi mình tổ chức tại đây. Chỉ 2-...     1
2950  Quán yên tĩnh có điều hoà nên ngày nóng dc trố...     1
2951  Đi tìm quán để ăn 5.6 lần không thấy quán.Nhìn...     0
2952  Bún mộc khá ngon, mộc thơm, vị đậm đà. Nước dù...     1
2953  Đi ăn với các phụ huynh nên chụp được mỗi một ...     1
2954  Quán nhỏ xíu. Đc tầm 6 bàn. Nhưng phở ăn khá đ...     1
2955  Hôm nay về Nam Định, thèm hải sản mới mò thử đ...     0
2956  🥗 Hôm cậu bạn tặng cho túi nem nắm, mình là tí...     1
2957  Quán cafe khá to nằm ngay mặt đường lớn. Chủ q...     1
2958  mỗii lần có người thân ngoài bắc vào nhà mình ...     1
2959  Ấn tượng bởi hương vị của bắp rang bơ\nNhiều l...     1
2960  Vừa qua lễ 30/4 nên có nhiều người quen đi du ...     1
2961                                      kẹo Sìu Châu.     1
2962  Mình thây quán này không gian rất thỏa mái tra...     1
2963  Trong cái nắng hè oi ả với nhiệt độ ngoài trời...     1

[2964 rows x 2 columns]

In [24]:
import matplotlib 
matplotlib.use('Agg')
import matplotlib.pyplot as plt

In [25]:
numpy_label = df['score'].values

In [26]:
plt.xlabel("number")
plt.ylabel("name_class")
plt.title("su phan bo cua cac class")
plt.hist(numpy_label,rwidth = 1,align ="left")
plt.savefig('demo.png')

In [27]:
with open("/home/hieuvt/Projects/Crawl_comments/vietnamese-stopwords-dash.txt", encoding="utf8") as input_file:
    x = input_file.readlines()
    removetable = str.maketrans('', '', '\n')
    stopwords = [s.translate(removetable) for s in x]
def prepocess(text):
    return preprocessor.preprocess(text)
def tokenize(text, stopwords):
        text_segmented = ViTokenizer.tokenize(text).split()
        text_segmented = [elem for elem in text_segmented if elem not in stopwords]
        return ' '.join(text_segmented)

In [28]:
reviews = []
score_comment = []

In [29]:
for i, text in enumerate(df['comment']):
#     score_comment.append(text['score'])
    a = prepocess(text)
    reviews.append(tokenize(a,stopwords))

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(min_df=5,max_df= 0.8,sublinear_tf=True)
tf.fit(reviews)
X = tf.transform(reviews)

In [31]:
Y = X.todense().A

In [32]:
type(Y)

numpy.ndarray

In [33]:
X_label = df['score'].values

In [34]:
type(X_label)

numpy.ndarray

In [35]:
X_train,X_test, Y_train, Y_test = train_test_split(Y,X_label,test_size = 0.2, random_state = 42)

In [36]:
import numpy as np
np.unique(Y_train)

array([0, 1], dtype=object)

In [37]:
Y_train.shape

(2371,)

In [38]:
test = pd.DataFrame()
test['y'] = Y_train

In [39]:
test.y.isnull().mean()

0.0

In [40]:
test.y.unique()

array([1, 0], dtype=object)

In [41]:
Y_train = Y_train.astype(int)

In [42]:
X_train

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.08550721, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [43]:
Y_train

array([1, 1, 1, ..., 1, 1, 0])

In [44]:
clf = svm.SVC(verbose=True, kernel='linear', probability=True, random_state=0, cache_size=2000, class_weight='balanced')
clf.fit(X_train,Y_train)
print(clf.n_support_)

[LibSVM][340 893]


In [45]:
Y_pred = clf.predict(X_test)

In [49]:
Y_test = Y_test.astype(int)

In [50]:
precision, recall, fscore, support = score(Y_test, Y_pred)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))
print('fscore: {}'.format(fscore))
print('support: {}'.format(support))

precision: [0.65034965 0.92666667]
recall: [0.73809524 0.89293362]
fscore: [0.69144981 0.90948746]
support: [126 467]
